services:
  app:
    image: dmitryshishkin/devops-for-developers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    command: make test
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:18.3-alpine3.23
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
