services:
  app:
    image: dmitryshishkin/devops-for-developers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
      platforms:
        - linux/amd64
        - linux/arm64
    command: make test
    ports:
      - "8080:8080"
